Improve dependency documentation (#141)
* Add comments to tox.ini and .travis.yml

* Tidy README.md

* Fix list of required packages in README.md

* Improve import error message

Only advise ./setup.py build if fract4dc is the problem.

* Ensure Cairo integration support is available

Else UI is not drawn correctly and multiple errors:
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html