travis: install required Ubuntu packages
Fix:

No package 'gobject-introspection-1.0' found

ValueError: Namespace Gdk not available
ValueError: Namespace Gtk not available